### ISSUE TITLE
Editable ADSR Parameters

### ISSUE THREAD

**Issue by MMMZZZZ** [MMMZZZZ/Syntherrupter#2]
## Description
Currently ADSR parameters are set at compile time. They should rather be customizable at runtime, by the user. 

## Tasks
- [x] Create GUI page which allows editing the parameter
- [x] Define communication protocol
- [x] Modify Tiva Firmware to receive and store changes.

## Related issues
*TBD*
