### ISSUE TITLE
MIDI Commands for all Syntherrupter Settings

### ISSUE THREAD

**Issue by MMMZZZZ** [MMMZZZZ/Syntherrupter#3]
## Description
Just like the note to stereo mapping is controlled by NRPs, all the other parameters should be modifiable by MIDI commands, too. This would allow to embed the settings in your MIDI files so that you can switch between files without the need to change anything by hand (like stereo reaches). 

## Tasks
- [x] Define MIDI SysEx and/or NRP commands for all settings
- [x] Add command processing to MIDI class
- [x] Send values to Nextion
- [x] Add option to send all current settings to the host. 

## Related issues
*TBD*

**Comment by MMMZZZZ** [comment]
Fully implemented with v4.2.0-beta.7
