### ISSUE TITLE
Compensation for non-linearity of Tesla Coils

### ISSUE THREAD

**Issue by MMMZZZZ** [MMMZZZZ/Syntherrupter#5]
## Description
Unlike speakers, tesla coils are nowhere near being linear in audio. Small ontimes cause almost no audio at all, and even when breakout occurs, the arc volume doesn't scale linearly with ontime. 

## Tasks
- [ ] Define "mapping standard", incl. number of points, ...
- [ ] Create User Interface to modify the mapping parameters
- [ ] Define communication protocol
- [ ] Modify Tiva Firmware to receive and store changes.

## Related issues
*TBD*
