### ISSUE TITLE
Firmware Version Check

### ISSUE THREAD

**Issue by MMMZZZZ** [MMMZZZZ/Syntherrupter#7]
## Description
Many firmware versions I released are not fully backwards compatible. Although I try to avoid this, the communication protocol between Nextion and Tiva is kept as tight as possible, which makes it difficult to add new features without changing existing commands. As of now the release notes - which you should absolutely read - indicate if a new release is not compatible. However it would maybe be useful to add such a check to the GUI, too. 

## Tasks
- [ ] Step 1: Basic version check and warning if Nextion and Tiva Firmware are different versions. 
- [ ] Step 2: Store in Firmware which versions are compatible and which are not. Display mismatch warning only if the versions are actually not compatible. 
  - [ ] Introduce Firmware numbers for easier lookup
- [ ] Step 3: Add information which features are not available and maybe disable them. 

## Related issues
*TBD*

**Comment by WayneSeng** [comment]
Im having problems with tiva firmware compatibility and nextion editor on version `4.2.0` and higher using nextion editor version `1.63.3`. The nextion editor remains black even after resetting microcontroller. Versions `4.1.4` and earlier work with nextion editor version `1.16.3`.

**Comment by MMMZZZZ** [comment]
@WayneSeng In case you missed it, I created a new issue for your bug report since it doesn't really fit into this issue. 

Kind regards,
Max
